name: logme
description: "A litle package be relax when your apps are running on production. Allways receive logs about what happen there through Telegram, slack and any other http REST API."

homepage: https://github.com/Ofceab-Studio/logme
repository: https://github.com/Ofceab-Studio/logme
version: 1.0.0

environment:
  sdk: '^3.0.0'
dependencies:
  auto_exporter: ^2.0.0
  dartz: ^0.10.1
  dotenv: ^4.2.0
  http: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.8

scripts:
  gen-build: 'dart run build_runner build && mv lib/export.dart lib/logme.dart'